### ISSUE TITLE
[TypeError: null is not an object (evaluating '_reactNativeAesGcmCrypto.default.decrypt')]

### ISSUE THREAD

**Issue by fukemy** [craftzdog/react-native-aes-gcm-crypto#5]
i got this error when run line:
```
const key = rsaKeyRef.current
            const iv = rsaKeyRef.current.slice(0, 16)
            const decrypt = AesGcmCrypto.decrypt(data, key, iv, '', true)
            .then(result => {
                console.log('decrypt result', result)
            }).catch(error => {
                console.log('decrypt error', error)
            })
            
```
the pod is install success
***Installing react-native-aes-gcm-crypto (0.2.1)***
 can u help?

**Comment by architectophile** [comment]
> i got this error when run line:
> 
> ```
> const key = rsaKeyRef.current
>             const iv = rsaKeyRef.current.slice(0, 16)
>             const decrypt = AesGcmCrypto.decrypt(data, key, iv, '', true)
>             .then(result => {
>                 console.log('decrypt result', result)
>             }).catch(error => {
>                 console.log('decrypt error', error)
>             })
>             
> ```
> 
> the pod is install success _**Installing react-native-aes-gcm-crypto (0.2.1)**_ can u help?

I have the same issue. Did you figure it out?

**Comment by Srikanth-Enuguru** [comment]
@architectophile @fukemy Are you able to fix this issue? I'm also facing the same.

FYI @craftzdog

**Comment by fukemy** [comment]
no sir i leaved this stupid lib
